{
 "title": "churn_predicti",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "api requests total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_requests_total)\r\n\r\n\r\n\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(api_requests_total[1m]))\r\n",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(prediction_latency_seconds_bucket[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{\"rate(api_requests_total[1m])\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(prediction_latency_seconds_bucket[1m])))\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}